2024-02-26 13:14:13.625641: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-02-26 13:14:13.656261: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-26 13:14:13.656294: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-26 13:14:13.657831: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-02-26 13:14:13.665188: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-02-26 13:14:13.665454: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-26 13:14:14.735736: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-02-26 13:14:45.765720: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2256] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
Train data shape: (65, 36209, 268)
Test data shape: (17, 36209, 268)
65 36209 268
Input Shape:  (36209, 268)
65 36209 268
Traceback (most recent call last):
  File "/home/nbrady/Desktop/deep_functional_net/scripts/ae_dense/ae_training_dense.py", line 123, in <module>
    decoder = models.Sequential([
              ^^^^^^^^^^^^^^^^^^^
  File "/home/nbrady/.conda/envs/rise/lib/python3.11/site-packages/tensorflow/python/trackable/base.py", line 204, in _method_wrapper
    result = method(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nbrady/.conda/envs/rise/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/nbrady/.conda/envs/rise/lib/python3.11/site-packages/keras/src/layers/reshaping/reshape.py", line 118, in _fix_unknown_dimension
    raise ValueError(msg)
ValueError: Exception encountered when calling layer "reshape" (type Reshape).

total size of new array must be unchanged, input_shape = [36209], output_shape = [36209, 268]

Call arguments received by layer "reshape" (type Reshape):
  â€¢ inputs=tf.Tensor(shape=(None, 36209), dtype=float32)
srun: error: gpu004: task 0: Exited with exit code 1
